### PR TITLE
Handle restorePreamble in cli prepare_and_send helper

### PR DESCRIPTION
**Pull request by paulbellamy**
### What

Handle the new `restorePreamble` return value from `simulateTransaction`

### Why

So that cli invoke still works if any entries need restoring

### Todo

- [ ] test it

### CODE REVIEW

**Review by 2opremio — APPROVED** [review]
Looks good, although I am missing some testing.

**Comment by tsachiherman** [comment]
@paulbellamy not sure why, but the mac tests are failing. could you fix those ?

**Comment by paulbellamy** [comment]
Seems like merging main fixed the mac tests.

**Comment by 2opremio** [comment]
@willemneal could you take over?

**Comment by mollykarcher** [comment]
Closing this in favor of #931

**Pull request closed without merging**
