### PR TITLE
feat: non-breaking updates to CLI

### PR DESCRIPTION
**Pull request by willemneal**
### What

The updates to xdr and RPC are out of sync with futurenet. So this is a collection of CLI related changes that are non-breaking.

### Why

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by 2opremio** [comment]
@willemneal I am lacking context or maybe I am just confused. The changes are not breaking but `main` is misaligned with futurenet. What do you meant exactly?

**Comment by willemneal** [comment]
@2opremio that is what I meant. I considered it a breaking change if the cli didn't work with futurenet

**Comment by 2opremio** [comment]
but you are merging them onto main, which is already misaligned with futurenet

**Comment by willemneal** [comment]
Oh sorry I should have mentioned at the top that this was never meant to be merged, but rather a reference to install the CLI from until the next release.

E.g.
```
cargo install --git https://github.com/ahalabs/soroban-tools --rev 2966e7ac9cbcc9f408b80f4aa21c3b76ccf064c6 soroban-cli

**Comment by willemneal** [comment]
No longer needed.

**Pull request closed without merging**
