### PR TITLE
Feat(CLI): add `key::Args` and `FullLedgerEntry`/`FullLedgerEntries`

### LINKED ISSUE #969: soroban-cli bump outputs an error while successful
### What version are you using?

```
soroban --version
soroban 20.0.0-rc1 (7d3b4175b1970f76455b4789797c2edc5f79e432)
soroban-env 20.0.0-rc1 (f19ef13363a1e0cbff7b100c0599a1d63dea88a6)
soroban-env interface version 85899345977
stellar-xdr 20.0.0-rc1 (d5ce0c9e7aa83461773a6e81662067f35d39e4c1)
xdr curr (9ac02641139e6717924fdad716f6e958d0168491)
```

### What did you do?

```
soroban --very-verbose contract bump  --id CB64D3G7SM2RTH6JSGG34DDTFTQ5CFDKVDZJZSODMCX4NJ2HV2KN7OHT \
  --source admin --network futurenet --durability persistent --ledgers-to-expire 60000
```

### What did you expect to see?

A successful message

### What did you see instead?

error: Ledger entry not found

If you run the same command with --very-verbose yout get
```
2023-09-18T05:59:51.771436Z TRACE soroban_cli::commands::contract::bump: network=Network { rpc_url: "https://rpc-futurenet.stellar.org:443", network_passphrase: "Test SDF Future Network ; October 2022" }
2023-09-18T05:59:51.798509Z TRACE soroban_cli::rpc: uri=https://rpc-futurenet.stellar.org:443/
2023-09-18T05:59:51.827419Z TRACE soroban_cli::rpc: Getting address GDGE7LBXW6YRTBVM7FWT4ZV5GBUQFY3D7BPIAF2F7V4MMHD4EK4645KM
2023-09-18T05:59:52.841814Z TRACE soroban_cli::rpc: account=AccountEntry { account_id: AccountId(PublicKeyTypeEd25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee))), balance: 99999968598, seq_num: SequenceNumber(148829206740998), num_sub_entries: 0, inflation_dest: None, flags: 0, home_domain: String32(StringM()), thresholds: Thresholds(01000000), signers: VecM([]), ext: V1(AccountEntryExtensionV1 { liabilities: Liabilities { buying: 0, selling: 0 }, ext: V2(AccountEntryExtensionV2 { num_sponsored: 0, num_sponsoring: 0, signer_sponsoring_i_ds: VecM([]), ext: V3(AccountEntryExtensionV3 { ext: V0, seq_ledger: 40590, seq_time: TimePoint(1695015865) }) }) }) }
2023-09-18T05:59:52.842677Z TRACE soroban_cli::rpc: Getting latest ledger
2023-09-18T05:59:53.746238Z TRACE soroban_cli::rpc: tx=Transaction { source_account: Ed25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee)), fee: 100, seq_num: SequenceNumber(148829206740999), cond: None, memo: None, operations: VecM([Operation { source_account: None, body: BumpFootprintExpiration(BumpFootprintExpirationOp { ext: V0, ledgers_to_expire: 60000 }) }]), ext: V1(SorobanTransactionData { ext: V0, resources: SorobanResources { footprint: LedgerFootprint { read_only: VecM([ContractData(LedgerKeyContractData { contract: Contract(Hash(7dc1ecdf9335199fc9918dbe0c732ce1d1146aa8f29cc9c360afc6a747ae94df)), key: LedgerKeyContractInstance, durability: Persistent })]), read_write: VecM([]) }, instructions: 0, read_bytes: 0, write_bytes: 0 }, refundable_fee: 0 }) }
2023-09-18T05:59:53.746295Z TRACE soroban_cli::rpc: tx=Tx(TransactionV1Envelope { tx: Transaction { source_account: Ed25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee)), fee: 100, seq_num: SequenceNumber(148829206740999), cond: None, memo: None, operations: VecM([Operation { source_account: None, body: BumpFootprintExpiration(BumpFootprintExpirationOp { ext: V0, ledgers_to_expire: 60000 }) }]), ext: V1(SorobanTransactionData { ext: V0, resources: SorobanResources { footprint: LedgerFootprint { read_only: VecM([ContractData(LedgerKeyContractData { contract: Contract(Hash(7dc1ecdf9335199fc9918dbe0c732ce1d1146aa8f29cc9c360afc6a747ae94df)), key: LedgerKeyContractInstance, durability: Persistent })]), read_write: VecM([]) }, instructions: 0, read_bytes: 0, write_bytes: 0 }, refundable_fee: 0 }) }, signatures: VecM([]) })
2023-09-18T05:59:54.462942Z TRACE soroban_cli::rpc: response=SimulateTransactionResponse { min_resource_fee: 5275, cost: Cost { cpu_insns: 0, mem_bytes: 0 }, results: [], transaction_data: "AAAAAAAAAAEAAAAGAAAAAX3B7N+TNRmfyZGNvgxzLOHRFGqo8pzJw2CvxqdHrpTfAAAAFAAAAAEAAAAAAAAAAAAAASgAAAAAAAAAAAAAAAA=", events: [], restore_preamble: None, latest_ledger: 40766, error: None }
2023-09-18T05:59:54.471566Z TRACE soroban_cli::rpc: tx=Tx(TransactionV1Envelope { tx: Transaction { source_account: Ed25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee)), fee: 6181, seq_num: SequenceNumber(148829206740999), cond: None, memo: None, operations: VecM([Operation { source_account: None, body: BumpFootprintExpiration(BumpFootprintExpirationOp { ext: V0, ledgers_to_expire: 60000 }) }]), ext: V1(SorobanTransactionData { ext: V0, resources: SorobanResources { footprint: LedgerFootprint { read_only: VecM([ContractData(LedgerKeyContractData { contract: Contract(Hash(7dc1ecdf9335199fc9918dbe0c732ce1d1146aa8f29cc9c360afc6a747ae94df)), key: LedgerKeyContractInstance, durability: Persistent })]), read_write: VecM([]) }, instructions: 0, read_bytes: 296, write_bytes: 0 }, refundable_fee: 0 }) }, signatures: VecM([DecoratedSignature { hint: SignatureHint(7c22b9ee), signature: Signature(BytesM(556d1bb80245239718efbba2fbe506c56768c73e078349aa8166883392dfe29d112bcbf5c9e96f374ec42d2546e0ef9f008751559ceed7282ccb897665916c0b)) }]) })
2023-09-18T06:00:00.709764Z TRACE soroban_cli::rpc: response=GetTransactionResponse { status: "SUCCESS", envelope_xdr: Some("AAAAAgAAAADMT6w3t7EZhqz5bT5mvTBpAuNj+F6AF0X9eMYcfCK57gAAGCUAAIdcAAAABwAAAAAAAAAAAAAAAQAAAAAAAAAZAAAAAAAA6mAAAAABAAAAAAAAAAEAAAAGAAAAAX3B7N+TNRmfyZGNvgxzLOHRFGqo8pzJw2CvxqdHrpTfAAAAFAAAAAEAAAAAAAAAAAAAASgAAAAAAAAAAAAAAAAAAAABfCK57gAAAEBVbRu4AkUjlxjvu6L75QbFZ2jHPgeDSaqBZogzkt/inREry/XJ6W83TsQtJUbg758Ah1FVnO7XKCzLiXZlkWwL"), result_xdr: Some("AAAAAAAAEDEAAAAAAAAAAQAAAAAAAAAZAAAAAAAAAAA="), result_meta_xdr: Some("AAAAAwAAAAAAAAACAAAAAwAAnz8AAAAAAAAAAMxPrDe3sRmGrPltPma9MGkC42P4XoAXRf14xhx8IrnuAAAAF0h2XSUAAIdcAAAABgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAACejgAAAABlB+O5AAAAAAAAAAEAAJ8/AAAAAAAAAADMT6w3t7EZhqz5bT5mvTBpAuNj+F6AF0X9eMYcfCK57gAAABdIdl0lAACHXAAAAAcAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAAnz8AAAAAZQfnXwAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAA=") }
2023-09-18T06:00:00.716512Z TRACE soroban_cli::commands::contract::bump: result=TransactionResult { fee_charged: 4145, result: TxSuccess(VecM([OpInner(BumpFootprintExpiration(Success))])), ext: V0 }
2023-09-18T06:00:00.716554Z TRACE soroban_cli::commands::contract::bump: meta=V3(TransactionMetaV3 { ext: V0, tx_changes_before: LedgerEntryChanges(VecM([State(LedgerEntry { last_modified_ledger_seq: 40767, data: Account(AccountEntry { account_id: AccountId(PublicKeyTypeEd25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee))), balance: 99999964453, seq_num: SequenceNumber(148829206740998), num_sub_entries: 0, inflation_dest: None, flags: 0, home_domain: String32(StringM()), thresholds: Thresholds(01000000), signers: VecM([]), ext: V1(AccountEntryExtensionV1 { liabilities: Liabilities { buying: 0, selling: 0 }, ext: V2(AccountEntryExtensionV2 { num_sponsored: 0, num_sponsoring: 0, signer_sponsoring_i_ds: VecM([]), ext: V3(AccountEntryExtensionV3 { ext: V0, seq_ledger: 40590, seq_time: TimePoint(1695015865) }) }) }) }), ext: V0 }), Updated(LedgerEntry { last_modified_ledger_seq: 40767, data: Account(AccountEntry { account_id: AccountId(PublicKeyTypeEd25519(Uint256(cc4fac37b7b11986acf96d3e66bd306902e363f85e801745fd78c61c7c22b9ee))), balance: 99999964453, seq_num: SequenceNumber(148829206740999), num_sub_entries: 0, inflation_dest: None, flags: 0, home_domain: String32(StringM()), thresholds: Thresholds(01000000), signers: VecM([]), ext: V1(AccountEntryExtensionV1 { liabilities: Liabilities { buying: 0, selling: 0 }, ext: V2(AccountEntryExtensionV2 { num_sponsored: 0, num_sponsoring: 0, signer_sponsoring_i_ds: VecM([]), ext: V3(AccountEntryExtensionV3 { ext: V0, seq_ledger: 40767, seq_time: TimePoint(1695016799) }) }) }) }), ext: V0 })])), operations: VecM([OperationMeta { changes: LedgerEntryChanges(VecM([])) }]), tx_changes_after: LedgerEntryChanges(VecM([])), soroban_meta: Some(SorobanTransactionMeta { ext: V0, events: VecM([]), return_value: Bool(false), diagnostic_events: VecM([]) }) })
```

### PR DESCRIPTION
**Pull request by willemneal**
### What

Created a new args struct for creating ledger keys. Also adds a new method and new types to the `rpc`, which helps return a struct containing an entry's expiration. 

- [x] Improve error handling bump/restore to ensure that checks a keys expiration if it fails to bump. Reporting to user that it was a no-op.

- Now durability is required, but we could could persistent as the default, as I'm sure it will be for most people.
- I also picked a max ledgers to bump based on trial and error, but could use on official one.
- And in the case where the ledger is before the expiration, the current expiration is returned. 
- Also updated read command to return the current expiration, though could use feedback on updating args if needed.

### Why
fix #969

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Review by 2opremio — APPROVED** [review]

**Comment by 2opremio** [comment]
@tsachiherman it seems you merged this with broken integration tests :(

**Comment by tsachiherman** [comment]
> @tsachiherman it seems you merged this with broken integration tests :(

Ahh.. I didn't notice that. I guess we'll need to either pr a fix or revert the change.

**Comment by 2opremio** [comment]
Actually they seem to have passed here but failed when run in main

**Comment by 2opremio** [comment]
See https://github.com/stellar/soroban-tools/issues/987 . @willemneal PTAL, I've assigned it to you

**Pull request merged**
