### PR TITLE
Revert "soroban-rpc: update go package dependencies"

### PR DESCRIPTION
**Pull request by 2opremio**
Reverts stellar/soroban-tools#1030

It enforces using Go 1.21 to compile soroban-tools

### CODE REVIEW

**Comment by 2opremio** [comment]
```
% go mod tidy -go=1.20   
go: finding module for package github.com/google/shlex
go: found github.com/google/shlex in github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: github.com/creachadair/mds@v0.2.3 requires go@1.21, but 1.20 is requested
```

**Comment by willemneal** [comment]
Why not upgrade to the 1.21?

**Comment by 2opremio** [comment]
Because we want to support the last 2 releases

**Comment by 2opremio** [comment]
OK, it seems the problem is stellar/go is also broken :(

**Pull request closed without merging**
