### PR TITLE
chore(bindings-ts): update to latest stellar-sdk & typescript; test in CI

### PR DESCRIPTION
**Pull request by chadoh**
### What

- CI: Add tests from https://github.com/AhaLabs/soroban-tools/pull/11 which didn't make it into https://github.com/stellar/soroban-tools/pull/973 due to the quickstart image not starting properly in CI (fixed in https://github.com/stellar/quickstart/pull/540))
- Update to latest `typescript` and `stellar-sdk`
- Update for latest CLI configuration
  - add explicit `--source` to all commands
  - stop using `soroban config identity`, use `soroban keys` instead

### Why

- CI will make sure the TS bindings stay functional
- latest deps r good

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by chadoh** [comment]
Most of these tests will be moving to stellar-sdk soon as part of https://github.com/stellar/js-stellar-sdk/pull/891. I'll circle back and update this PR with any needed changes after that lands.

**Comment by chadoh** [comment]
Will be implemented as part of https://github.com/stellar/js-stellar-sdk/pull/891, wherever it ends up living

**Comment by chadoh** [comment]
Actually, we may still want a few tests here. No reason to wait on implementing this; I'll get back to it now that https://github.com/stellar/quickstart/pull/540 has been released.

**Comment by chadoh** [comment]
Looks like most of the jobs are not running right now. Not sure why. @mollykarcher do I just need to wait a little while longer, or did I do something wrong?

**Comment by mollykarcher** [comment]
@chadoh I'm honestly not sure what/if you did anything wrong. Perhaps some weird github idiosyncrasy with the combo of retargetting + force pushing + move from draft sequence. Close/reopen on my part seems to have kicked it off though

**Review by Shaptic — APPROVED** [review]
I think this needs a 

```bash
make typescript-bindings-fixtures
```

run but otherwise it's good2go.

If you took this opportunity to `stellar-sdk` :arrow_right: `@stellar/stellar-sdk`, though, it would shrink the number of dependency dupes and possible XDR mismatches (since `@stellar/freighter-api` uses the `@stellar/` variant). Should be an easy set of renames!

I'll approve nonetheless.

**Comment by chadoh** [comment]
Good idea with the `@stellar/stellar-sdk` switch. Updated!

**Pull request merged**
