### PR TITLE
soroban-rpc: Fix ledgerentry visibility bug

### PR DESCRIPTION
**Pull request by paulbellamy**
### What

Fix a ledger entry visibility bug introduced in #846.

### Why

Ledger Entries should be visible when `currentLedger == expirationLedgerSeq` (according to https://soroban.stellar.org/docs/fundamentals-and-concepts/state-expiration#expiration-ledger). But the code previously made it a bit unclear which ledger was LatestClosed vs Current (which led to the bug).

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by 2opremio** [comment]
Nice, thanks! Could you also fix the off-by-one printout of `TestSimulateTransactionBumpAndRestoreFootprint` ?

```
t.Log("waiting for ledger entry to expire at ledger", entry.MustContractData().ExpirationLedgerSeq+1)
```

should really be

```
t.Log("waiting for ledger entry to expire at ledger", entry.MustContractData().ExpirationLedgerSeq)
```

**Review by 2opremio — APPROVED** [review]

**Review by tsachiherman — APPROVED** [review]

**Comment by 2opremio** [comment]
The integration tests failed before merging :S

**Comment by 2opremio** [comment]
Specifically in:

```
        if !expirable_entry.has_expired(current_ledger_seq) {
            // noop (the entry hadn't expired)
            continue;
        }
```

**Comment by 2opremio** [comment]
Can we revert this until we figure it out?

**Comment by 2opremio** [comment]
Specifically it failed at https://github.com/stellar/soroban-tools/actions/runs/5926341294/job/16068360612 with:

```
2023-08-21T13:15:20.7012344Z     transaction_test.go:251: 
2023-08-21T13:15:20.7013384Z         	Error Trace:	/home/runner/work/soroban-tools/soroban-tools/cmd/soroban-rpc/internal/test/transaction_test.go:251
2023-08-21T13:15:20.7015736Z         	            				/home/runner/work/soroban-tools/soroban-tools/cmd/soroban-rpc/internal/test/simulate_transaction_test.go:785
2023-08-21T13:15:20.7016288Z         	Error:      	Not equal: 
2023-08-21T13:15:20.7016772Z         	            	expected: "SUCCESS"
2023-08-21T13:15:20.7017271Z         	            	actual  : "FAILED"
2023-08-21T13:15:20.7017626Z         	            	
2023-08-21T13:15:20.7017980Z         	            	Diff:
2023-08-21T13:15:20.7018508Z         	            	--- Expected
2023-08-21T13:15:20.7018926Z         	            	+++ Actual
2023-08-21T13:15:20.7019395Z         	            	@@ -1 +1 @@
2023-08-21T13:15:20.7019847Z         	            	-SUCCESS
2023-08-21T13:15:20.7020235Z         	            	+FAILED
2023-08-21T13:15:20.7020897Z         	Test:       	TestSimulateTransactionBumpAndRestoreFootprint
```

and at simulate_transaction_test.go:785 is where we send the restorefootprint operation

**Pull request merged**
