### PR TITLE
Support StrKey format for "contractIds" field in getEvents request

### LINKED ISSUE #796: soroban-rpc: the`contactIds` field in `getEvents` request should support StrKey format.
### What problem does your feature solve?
In [SEP-23](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0023.md), `STRKEY_CONTRACT` has already been added. I think we should add the corresponding support.

### What would you like to see?
Request
```diff
{
    "jsonrpc": "2.0",
    "id": "test",
    "method": "getEvents",
    "params": {
        "startLedger": 1800,
        "cursor": {
            "limit": 10,
            "cursor": "0000007799660613632-0000000000"
        },
        "filters": [{
           "type": "contract",
-          "contractIds": ["607682f2477a6be8cdf0fdf32be13d5f25a686cc094fd93d5aa3d7b68232d0c0"],
+          "contractIds": ["CBQHNAXSI55GX2GN6D67GK7BHVPSLJUGZQEU7WJ5LKR5PNUCGLIMAO4K"],
           "topics":[["AAAADwAAAAdDT1VOVEVSAA==","AAAADwAAAAlpbmNyZW1lbnQAAAA="]]
        }]
    }
}
```

Response
```diff
{
    "type": "contract",
    "ledger": "116",
    "ledgerClosedAt": "2023-07-23T14:47:09Z",
-   "contractId": "607682f2477a6be8cdf0fdf32be13d5f25a686cc094fd93d5aa3d7b68232d0c0",
+   "contractId": "CBQHNAXSI55GX2GN6D67GK7BHVPSLJUGZQEU7WJ5LKR5PNUCGLIMAO4K",
    "id": "0000000498216210432-0000000000",
    "pagingToken": "0000000498216210432-0000000000",
    "topic": [
        "AAAADwAAAAdDT1VOVEVSAA==",
        "AAAADwAAAAlpbmNyZW1lbnQAAAA="
    ],
    "value": {
        "xdr": "AAAAAwAAAAQ="
    },
    "inSuccessfulContractCall": true
}
```

### What alternatives are there?
None.

### PR DESCRIPTION
**Pull request by overcat**
### What

Support StrKey format for "contactIds" field in getEvents request.

### Why
resolve #796 

### Known limitations
N/A

### CODE REVIEW

**Comment by overcat** [comment]
I think the reason why CI did not pass is on the JS side, maybe we should revert https://github.com/stellar/system-test/commit/68baf81057a59fac826057ad1c0c88b46e9f593b

**Comment by overcat** [comment]
Before merging this PR, we need to merge https://github.com/stellar/system-test/pull/71 first, and then update the version of system-test in this project.

**Review by Shaptic — APPROVED** [review]
outstanding :clap:

**Comment by Shaptic** [comment]
@overcat you can use a gitref to master for the system-test so that we don't need to tag a release

**Comment by overcat** [comment]
> @overcat you can use a gitref to master for the system-test so that we don't need to tag a release

Thank you, now the CI has turned green 🟢.

**Pull request merged**
