### PR TITLE
Add GitHub linting for GO code

### PR DESCRIPTION
**Pull request by tsachiherman**
### What

Add GitHub linting for GO code

### Why

Better code, less bugs.

### Known limitations

N/A

### CODE REVIEW

**Comment by sreuland** [comment]
can some content be added to README.md to mention linting config/requirements, but also, an example of how to run the same linting locally to pre-check before pushing?

**Review by sreuland — APPROVED** [review]
nice improvement, left one comment just for consideration of extra docs in readme, thanks!

**Comment by leighmcculloch** [comment]
> can some content be added to README.md to mention linting config/requirements, but also, an example of how to run the same linting locally to pre-check before pushing?

Alternatively we could add a `lint` target to `Makefile` which runs the command.

**Comment by tsachiherman** [comment]
> > can some content be added to README.md to mention linting config/requirements, but also, an example of how to run the same linting locally to pre-check before pushing?
> 
> Alternatively we could add a `lint` target to `Makefile` which runs the command.

exactly.

**Pull request merged**
