### PR TITLE
fix(rpc): actually use RPC in CLI tests; add icmd and assertCmd for better error reporting

### PR DESCRIPTION
**Pull request by willemneal**
### What

Correctly name the env vars for setting the network configuration when invoking the CLI.

Also fix auth bug for deploys.

`runCLICommand` now uses `icmd` to execute CLI commands and `shlex` to parse the input string. 'assertCmd' wraps a call to `runCLICommand` and `require.NoError`, passing the stderr writer to lazily write with error, returning stdout as a `string`.

### Why

It currently is using the sandbox.

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by willemneal** [comment]
I'm currently getting when trying to deploy.
```
        	            	error: transaction submission timeout
```

**Review by 2opremio — APPROVED** [review]

**Comment by 2opremio** [comment]
I have been looking into this and it seems soroban-rpc receives a "PENDING" status when submitting the contract creation transaction submission but core never sends meta for it.

I see three possibilities:
1. The transaction fails but Core is responding with "PENDING" instead of "FAIL"
2. The transaction fails later on and Core fails to send the corresponding meta.
3. Core does emit the meta later on but soroban-rpc fails to obtain it.

**Comment by 2opremio** [comment]
It seems to have worked once! https://github.com/stellar/soroban-tools/actions/runs/6149908369/job/16686748093?pr=942

So maybe it is a concurrency problem.

But it still fails locally for me.

**Comment by 2opremio** [comment]
Here are the debug logs: [core-logs-debug.txt](https://github.com/stellar/soroban-tools/files/12579803/core-logs-debug.txt)

**Comment by 2opremio** [comment]
Here is the meaningful part of the logs:

```
2023-09-11T19:40:28.293 GD5KD [Tx INFO] applying ledger 17 (classic phase: 0 component(s): [], soroban phase: 1 component(s): [{discounted txs:1, ops:1, base_fee:100}])
2023-09-11T19:40:28.294 GD5KD [Tx DEBUG]  tx#0 = 935a1d ops=1 txseq=55834574850 (@ GDIY6)
2023-09-11T19:40:28.314 GD5KD [Ledger DEBUG] Ledger: 17 txs: 1, ops: 1, prefetch hit rate (%): 0
2023-09-11T19:40:28.319 GD5KD [Bucket DEBUG] Adopting bucket file buckets/tmp/bucket-0af91ebc98c2ef6d/tmp-bucket-1f6ead688f743a2e.xdr as buckets/bucket-0415c30a7fa5582dd7a27a505282cb339c8a30625055b1e9375f10ac9267c631.xdr
2023-09-11T19:40:28.321 GD5KD [Bucket DEBUG] Deleting bucket file buckets/tmp/bucket-0af91ebc98c2ef6d/tmp-bucket-54dd1ef87af15e42.xdr that is redundant with existing bucket
2023-09-11T19:40:28.321 GD5KD [Perf DEBUG] Bucket merge on level 0 finished in 0.001333583 seconds (0.13335829999999999% of available time)
2023-09-11T19:40:28.323 GD5KD [Ledger DEBUG] Advancing LCL: [seq=16, hash=278066] -> [seq=17, hash=b69244]
2023-09-11T19:40:28.328 GD5KD [Perf DEBUG] Applied ledger in 0.036461917 seconds
2023-09-11T19:40:28.328 GD5KD [Ledger INFO] Closed ledger: [seq=17, hash=b69244]
2023-09-11T19:40:28.328 GD5KD [Ledger DEBUG] LedgerManager::valueExternalized LCL advanced 16 -> 17
2023-09-11T19:40:28.328 GD5KD [Tx DEBUG] Dropping de59fa transaction
2023-09-11T19:40:28.328 GD5KD [Tx DEBUG] Ban applied transaction de59fa
```

It seems the transaction is dropped/banned!

**Comment by 2opremio** [comment]
OK, I think I know what is happening.

After the last transaction is sent, there soroban-rpc stops ingesting ledgers. I don't know if it's due to a problem in soroban-rpc or due to a problem in captive core.

The ledger closing log from captive core is:

```
time="2023-09-11T22:10:33.601+02:00" level=info msg="Ledger: Closed ledger: [seq=16, hash=ae68cb]" pid=66079 subservice=stellar-core
time="2023-09-11T22:10:33.602+02:00" level=debug msg="Ingested ledger 16" pid=66079
time="2023-09-11T22:10:33.602+02:00" level=info msg="Ingesting ledger 17" pid=66079
```

But ... the last transaction is included in ledger 17 acording to the Core logs.

My guess is that, for some reason, stellar-core stops producing meta.

**Comment by 2opremio** [comment]
I can confirm that we get stuck at `s.ledgerBackend.GetLedger(ctx, 15)`

**Comment by 2opremio** [comment]
It turns out the problem was caused by a mismatch in the commit of Core vs Captive Core.

**Pull request merged**
